title: About me
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Abubakar Usman"
job: " junior Pentester "

phone_number: +2349030327468
address: Yola North, Nigeria
email: abu3274768@gmail.com
linkedin_username: abubakar-usman-011115263
github_username: ethic-bakeery
instagram_username: _bakeery
twitter_username: fckbwn
facebook_username: Bakeery
youtube_username: youtube
blog_url: https://ethic-bakeery.github.io/

baseurl: /my-resume

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
